dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - echo $TRAVIS_BUILD_DIR
  - cp $TRAVIS_BUILD_DIR/src/environments/environments.ts $TRAVIS_BUILD_DIR/src/environments/environments.prod.ts
install:
  - npm install
script:
  - npm run prod
